"""fill models

Revision ID: 362f8d0897a9
Revises: e3c97faa0c42
Create Date: 2021-09-12 16:35:33.213861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362f8d0897a9'
down_revision = 'e3c97faa0c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'contact_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('phones', 'phone',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', 'phone',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('contacts', 'contact_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
