# Generated by Django 3.2.8 on 2021-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('date_of_deposit', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('expenses_amount', models.IntegerField()),
                ('expenses_comment', models.TextField(max_length=200)),
                ('date_of_expenses', models.DateTimeField()),
            ],
        ),
    ]
