# Generated by Django 3.2.8 on 2021-10-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_con', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='income',
            table='incomes_table',
        ),
        migrations.AlterModelTable(
            name='spending',
            table='expensis_table',
        ),
    ]
