# Generated by Django 3.2.8 on 2021-10-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_con', '0003_auto_20211017_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spending',
            name='expenses_amount',
            field=models.FloatField(),
        ),
    ]
